name: NotzExcavate
version: '1.2'
main: dev.kaato.notzexcavate.NotzExcavate
depend: [PlotSquared]
#api-version: '1.18'

commands:
  nexcavate:
    usage: /nexcavate
    aliases:
      - nex
      - nescavar
      - nes
  excavate:
    usage: /excavate
    aliases:
      - excavator
      - status
permissions:
  notzexcavate.admin:
    default: false
  notzexcavate.useany:
    default: false