name: NotzExcavate
version: '1.1'
main: notzexcavate.Main
commands:
  nexcavate:
    usage: /nexcavate
    aliases:
      - nex
      - nescavar
      - nes
permissions:
  notzexcavate.admin:
    default: false
  notzexcavate.useany:
    default: false